### ISSUE TITLE
bug: implementation is dependent on IPFS default hash method not changing

### ISSUE THREAD

**Issue by felixwatts** [ProjectProvenance/proof-points#9]
Hash should be calculated ion a way that is under our control and will always match the spec

IPFS hashes the data using any hashing alg it likes and returns the multihash encoding of the hash. This means that different versions or implementations of IPFS might return different hashes for the same data. (you can still look up the data, whichever hash you have of it)

Currently we depend on the assumption that IPFS will always calculate the same hash for the same data. We can make this assumption hold true with a command line arg to ipfs that forces it to use a given hashing alg.

**Comment by pmackay** [comment]
@felixwatts did you look into this further? Should we try to resolve?

**Comment by felixwatts** [comment]
This is fixed - we now use a parameter to make sure the SHA-256 hash method is used
